
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Profile: 'Profile',
  PaymentRequest: 'PaymentRequest',
  Link: 'Link',
  Experience: 'Experience',
  Project: 'Project',
  Skill: 'Skill',
  Education: 'Education',
  PageView: 'PageView'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ProfileScalarFieldEnum = {
  id: 'id',
  clerkId: 'clerkId',
  username: 'username',
  fullName: 'fullName',
  headline: 'headline',
  summary: 'summary',
  location: 'location',
  email: 'email',
  phone: 'phone',
  avatarUrl: 'avatarUrl',
  openToWork: 'openToWork',
  template: 'template',
  themeConfig: 'themeConfig',
  isPublished: 'isPublished',
  plan: 'plan',
  planExpiresAt: 'planExpiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProfileScalarFieldEnum = (typeof ProfileScalarFieldEnum)[keyof typeof ProfileScalarFieldEnum]


export const PaymentRequestScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  plan: 'plan',
  amount: 'amount',
  utr: 'utr',
  status: 'status',
  createdAt: 'createdAt',
  reviewedAt: 'reviewedAt'
} as const

export type PaymentRequestScalarFieldEnum = (typeof PaymentRequestScalarFieldEnum)[keyof typeof PaymentRequestScalarFieldEnum]


export const LinkScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  kind: 'kind',
  label: 'label',
  url: 'url',
  sort: 'sort'
} as const

export type LinkScalarFieldEnum = (typeof LinkScalarFieldEnum)[keyof typeof LinkScalarFieldEnum]


export const ExperienceScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  title: 'title',
  organization: 'organization',
  location: 'location',
  startDate: 'startDate',
  endDate: 'endDate',
  bullets: 'bullets',
  sort: 'sort'
} as const

export type ExperienceScalarFieldEnum = (typeof ExperienceScalarFieldEnum)[keyof typeof ExperienceScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  name: 'name',
  tagline: 'tagline',
  description: 'description',
  bullets: 'bullets',
  tech: 'tech',
  liveUrl: 'liveUrl',
  repoUrl: 'repoUrl',
  imageUrl: 'imageUrl',
  featured: 'featured',
  source: 'source',
  githubRepo: 'githubRepo',
  sort: 'sort'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const SkillScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  category: 'category',
  items: 'items',
  sort: 'sort'
} as const

export type SkillScalarFieldEnum = (typeof SkillScalarFieldEnum)[keyof typeof SkillScalarFieldEnum]


export const EducationScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  institution: 'institution',
  degree: 'degree',
  startYear: 'startYear',
  endYear: 'endYear',
  score: 'score',
  sort: 'sort'
} as const

export type EducationScalarFieldEnum = (typeof EducationScalarFieldEnum)[keyof typeof EducationScalarFieldEnum]


export const PageViewScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  kind: 'kind',
  ref: 'ref',
  createdAt: 'createdAt'
} as const

export type PageViewScalarFieldEnum = (typeof PageViewScalarFieldEnum)[keyof typeof PageViewScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

